### ISSUE TITLE
Setup initial testing infrastructure

### ISSUE THREAD

**Issue by Totktonada** [tarantool/httpng#13]
- Decide which kinds of testing we need: unit, functional, integration, ..?
- Decide on testing framework(s): CTest, [luatest](https://github.com/tarantool/luatest/), pytest.
- Implement one test of each kind.
- Add `make test` target to run all tests (see also https://github.com/tarantool/tarantool/commit/a753f258f208f5070e5516a7162ed071e5948b3c).
- Integrate testing into CI (consider using of [setup-tarantool](https://github.com/tarantool/setup-tarantool)).
  - Don't forget to test the module against different tarantool versions (see also https://github.com/tarantool/setup-tarantool/issues/12 and https://github.com/tarantool/setup-tarantool/issues/9).
  - Don't forget to run testing on Mac OS.
- Consider testing of RPM / Deb packages (either implement, or postpone with an issue, or decline with a reason).
- Elaborate further testing plan (and file issues).

Review chain: @void234, @Totktonada.

**Comment by void234** [comment]
Created #209 for RPM/Deb packages testing (we do not have such packages yet).

I do not believe that we need unit testing, at least not at this stage of development. httpng is almost exclusively about passing data between threads and fibers of Tarantool and libh2o, very few things can be tested by unit tests. It is much more efficient to use integration and load tests with asserts and ASAN - and we already have that.
