### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by void234** [tarantool/httpng#18]
Stop or reconfigure running HTTP(S) server: add/remove listening IPs/ports, keys/certificates, virtual hosts, paths, handlers.

**Comment by Totktonada** [comment]
Am I understood the issue right: we consider the following three cases here?

1. Reconfiguration (a second and a next `httpng.cfg()` call).
2. Stopping (`httpng.stop()` or kinda; after #6).
3. Unloading / reloading of the module (`package.loaded.httpng = nil`).

**Comment by Totktonada** [comment]
> Am I understood the issue right: we consider the following three cases here?
> 
> <...>

@void234?

**Comment by void234** [comment]
> Am I understood the issue right: we consider the following three cases here?
> 
>     1. Reconfiguration (a second and a next `httpng.cfg()` call).
> 
>     2. Stopping (`httpng.stop()` or kinda; after #6).
> 
>     3. Unloading / reloading of the module (`package.loaded.httpng = nil`).

My apologies for the late answer, somehow I have missed this message.
"1." is exactly what I am implementing.
"2." has been implemented as part of #6 - httpng.shutdown(), but, of course, there were some changes and bug fixes since then.
I haven't looked into "3." yet.

**Comment by Totktonada** [comment]
Regarding '3. Unloading / reloading of the module (`package.loaded.httpng = nil`)':

I looked on the question in context of the configuration storage client and filed the [issue](https://github.com/tarantool/conf/issues/2) with background information and thoughts around. It may contain useful information.

My main point is that here (in httpng) we should have clear and documented behaviour what is going on, when a user (an application developer) reloads the module this way. However, to be honest, I'm not ready to tell, which exact behaviour we should implement.

It worth to pay attention to the fact that cartridge's hot reload [removes](https://github.com/tarantool/cartridge/blob/14b2aa0c76dc2914ea00433754e24b00a5447efd/cartridge/hotreload.lua#L176-L192) old http server routes, while it looks as a task that an http server should perform on its own. Don't know. It requires further investigation.

**Comment by Totktonada** [comment]
Please, remind me, what else remains to do within this issue?

**Comment by void234** [comment]
> Please, remind me, what else remains to do within this issue?

I believe it is better to close this issue and create new ones as necessary.
I have created #219 as a major one. Not sure we need to add/remove IPs/ports without restarting the server. Adding/removing routes (paths) would be implemented as part of #4 as a replacement for `sites`.
