### ISSUE TITLE
Shutdown

### ISSUE THREAD

**Issue by void234** [tarantool/httpng#6]
Right now there is no ability to shutdown HTTP(S) server - connections are not terminated, threads are not stopped, memory is not deallocated.

**Comment by Totktonada** [comment]
What remains to do after PR #64?

**Comment by void234** [comment]
> What remains to do after PR #64?

Programmatic shutdown from Lua (one-liner, done but not yet committed).
Stability fixes (in progress), resource leak fixes (todo).

**Comment by void234** [comment]
Done pending further automated testing implementation - minor memory leaks etc likely
